import { Inter } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import Footer from "../components/Footer";
import "./globals.css";
import React from "react";
import Script from "next/script";
// import { useState } from "react";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "800"],
  variable: ["--playfair-font"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={[inter.className, playfair.className]}>
          {children}
          <Footer />
        </body>
      </html>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </>
  );
}
